# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbs2ctx',
                'doc_host': 'https://AnswerDotAI.github.io',
                'git_url': 'https://github.com/AnswerDotAI/nbs2ctx',
                'lib_path': 'nbs2ctx'},
  'syms': {'nbs2ctx.core': {'nbs2ctx.core.foo': ('core.html#foo', 'nbs2ctx/core.py')}}}
